### PR TITLE
Add support to build Android with ndk 26 and Rust 1.76

### LINKED ISSUE #2883: Ensure Android works with latest rust

### PR DESCRIPTION
**Pull request by clemens-msupply**
The remaining issue was that ring 0.16.20 was not compiling correctly. To make it work some env variables needed to be pointed to the correct AR and CC binaries.

Fixes #2883

The remaining issue was that ring 0.16.20 was not compiling correctly. To
make it work some env variables needed to be pointed to the correct AR
and CC binaries.

Note, this might break the compilation using the older Rust and ndk versions, but I think if this patch is working for everybody we should just require the latest versions.

## Testing
- Install Android NDK 26.1.10909125
- Update to latest Rust (`rustup default stable`)
- Delete the `client/packages/android/server-lib` directory 
- Update your NDK_BIN env variable to the correct (check it points to the new ndk 26: `echo $NDK_BIN`)
- Compile the apk `yarn android:build:debug` (from client directory)
- Install the debug apk and test if it is running

### CODE REVIEW

File: client/packages/android/build_remote_server_libs.sh [hunk 1]
```diff
@@ -3,6 +3,10 @@ set -e
 
 # See server/android/README/md for more details
 
+# The following env variables are needed to build ring 0.16.20:
+export AR=${NDK_BIN}/llvm-ar
+export CC_armv7_linux_androideabi=${NDK_BIN}/armv7a-linux-androideabi22-clang
```
Comment (clemens-msupply) [inline client/packages/android/build_remote_server_libs.sh:8]: Not so nice to have the 22 hard coded here and in `android/.cargo/config.toml`

**Comment by clemens-msupply** [comment]
Just noticed, when it's working for you, I also need to update the Readmes...

**Comment by roxy-dao** [comment]
Can you update the Android READMEs with the new versions~? Thanks!

File: server/Cargo.toml [hunk 2]
```diff
@@ -11,7 +11,7 @@ async-graphql = { version = "3.0.35", features = ["dataloader", "chrono"] }
 async-graphql-actix-web = "3.0.35"
 async-trait = "0.1.30"
 chrono = { version = "0.4.23", features = ["serde"] }
-reqwest = { version = "0.11.10", features = ["json"] }
+reqwest = { version = "0.11.10", features = ["json", "rustls-tls"], default-features = false }
```
Comment (clemens-msupply) [inline server/Cargo.toml:14]: This removes the openssl dependency

**Comment by mark-prins** [comment]
@jmbrunskill would you mind trying this as well? 
It's working for me, but not for @roxy-dao. would be good to have someone else try it out 🙏

**Review by mark-prins — APPROVED** [review]
👍 LGTM! I can now build with 1.76!
as discussed, would be good to wait for another person to validate before merging this one

**Comment by jmbrunskill** [comment]
With rust 1.75 I get this...

```
@openmsupply-client/android:   |: error[E0463]: can't find crate for `core`
@openmsupply-client/android:   |
@openmsupply-client/android:   = note: the `aarch64-linux-android` target may not be installed
@openmsupply-client/android:   = help: consider downloading the target with `rustup target add aarch64-linux-android`
@openmsupply-client/android: error[E0463]: can't find crate for `compiler_builtins`
@openmsupply-client/android: error[E0463]: can't find crate for `core`
@openmsupply-client/android:   |
@openmsupply-client/android:   = note: the `armv7-linux-androideabi` target may not be installed
@openmsupply-client/android:   = help: consider downloading the target with `rustup target add armv7-linux-androideabi`
@openmsupply-client/android: For more information about this error, try `rustc --explain E0463`.
@openmsupply-client/android: error: could not compile `cfg-if` (lib) due to 2 previous errors
@openmsupply-client/android: warning: build failed, waiting for other jobs to finish...
```

1.76 works for me though! Can't see anything obvious in the release notes to explain it though.

Perhaps we can update the rust version field in the cargo.toml file for future reference?
https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

I'm happy to merge.

**Review by jmbrunskill — APPROVED** [review]
Works good with 1.76

**Comment by mark-prins** [comment]
thanks @jmbrunskill!
hopefully that error might just be needing `rustup target add aarch64-linux-android` and `rustup target add armv7-linux-androideabi` for 1.75

**Comment by roxy-dao** [comment]
Yeah... mine still doesn't work. Always looking for v1.68 for some reason. Removed 1.68 and running `yarn android:build:debug` would reinstall it... cargo clean doesn't work either... 🤔

**Comment by clemens-msupply** [comment]
> Yeah... mine still doesn't work. Always looking for v1.68 for some reason. Removed 1.68 and running `yarn android:build:debug` would reinstall it... cargo clean doesn't work either... 🤔

What mac version (hardware/software) do you have? do you have the same as Mark?

**Comment by roxy-dao** [comment]
> What mac version (hardware/software) do you have? do you have the same as Mark?

MacOS 14.2.1 (23C71)

**Comment by mark-prins** [comment]
same here - on an M1 Pro.
What about `rustup show` and `cargo version`?
```
cargo version
cargo 1.76.0 (c84b36747 2024-01-18)

rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/m2/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
1.65-x86_64-apple-darwin
1.71-x86_64-apple-darwin
1.52.1-x86_64-apple-darwin
1.64.0-x86_64-apple-darwin
1.65.0-x86_64-apple-darwin
1.71.0-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-linux-android
armv7-linux-androideabi
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.76.0 (07dca489a 2024-02-04)
```

**Comment by roxy-dao** [comment]
I remove 1.68 every time but it keeps coming back 👀 

Screenshot 2024-02-20 at 09 00 27

**Comment by roxy-dao** [comment]
Update: Server builds now, and running the build script works but `yarn android:build:debug` does not work

**Review by roxy-dao — APPROVED** [review]
Managed to get it to build~ Thanks Mark for all the help <3 and Clemens for the changes <3 /o/ (Went nuclear and nuked my rust installation and re-installed everything and set the envs again)

**Comment by clemens-msupply** [comment]
thanks Roxy and Mark for all the testing!
