### PR TITLE
Fix plugin compilations and docker build

### LINKED ISSUE #8323: Error when building plugins after recent Mui updates
## What went wrong? 😲

When building front-end plugins using cli `generate-and-install-plugin-bundle` or `generate-plugin-bundle`, we are now getting the following error:

```
ERROR in ../../../../../node_modules/@mui/x-date-pickers/esm/internals/hooks/useToolbarOwnerState.js 3:0-49
Module not found: Error: Can't resolve '@mui/system/RtlProvider' in '/Users/carl/GitHub/open-msupply/client/node_modules/@mui/x-date-pickers/esm/internals/hooks'
Did you mean 'index.js'?
BREAKING CHANGE: The request '@mui/system/RtlProvider' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ../../../../../node_modules/@mui/x-date-pickers/esm/DatePicker/DatePickerToolbar.js 17:0-82 73:21-41
 @ ../../../../../node_modules/@mui/x-date-pickers/esm/DatePicker/index.js 2:0-59 2:0-59
 @ ../../../../../node_modules/@mui/x-date-pickers/esm/index.js 28:0-38 28:0-38
 @ ../../../../common/src/ui/components/index.ts 26:0-66 46:0-375 46:0-375
 @ ../../../../common/src/ui/index.ts 4:0-29 4:0-29
 @ ../../../../common/src/index.ts 6:0-21 6:0-21
 @ consume shared module (default) @openmsupply-client/common@* (singleton) (fallback: ../../../../common/src/index.ts) (eager)
 @ ./src/AggregateAmcInfo/AggregateAmcInfo.tsx 1:0-252 8:30-47 9:21-37 22:20-30 28:18-33 36:19-36 44:19-36 51:18-33 52:19-36 59:18-33 60:19-36 74:24-39 78:18-33 79:19-36 86:32-41 90:22-36 93:36-54 94:32-56 95:36-39 100:40-53 100:70-86
 @ ./src/plugin.tsx 2:0-74 9:23-42
```

This is only occurring on the 2.9 branch, with updated Mui Date pickers. It still works correctly on the 2.8.3 RC branch

## Expected behaviour 🤔

Should build correctly

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run a command to build plugins, e.g. `cargo run --bin remote_server_cli -- generate-and-install-plugin-bundle -i '../client/packages/plugins/<plugin-repo>/frontend' --url 'http://localhost:8000' --username demo --password <password>
2. Wait for it...
3. Error!

## Your environment 🌱

- Open mSupply Version: 2.9.0 (dev)

### LINKED ISSUE #8481: Plugin compilation errors
## What went wrong? 😲

Various plugin compilation errors:

For CIV: 
```
BREAKING CHANGE: The request '@mui/material/styles' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
```

For ST (after running yarn generate):
```
[tsl] ERROR in /Users/andreievg/Documents/playground/android_setup/open-msupply/client/packages/common/src/utils/index.ts(14,15)
      TS6142: Module './BarcodeScannerContext' was resolved to '/Users/andreievg/Documents/playground/android_setup/open-msupply/client/packages/common/src/utils/BarcodeScannerContext.tsx', but '--jsx' is not set.
```

Also ST compilation errors because backend types are not up to date

I was also getting an error while compiling from docker image, but when I manually enter docker container and do 'yarn install' in client folder it seems to work, so also would like to do yarn install inside docker container before publishing

## Expected behaviour 🤔

Plugin compilations work

## How to Reproduce 🔨

Bring both plugins in current repo (via submodule command).

Run yarn and yarn generate from client.

For ST go to backend/latest, run yarn then yarn build-plugin (see errors)

For CIV go to frontend/latest, run yarn then yarn build-plugin (see errors)

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #8481 
Fixes #8323 

# 👩🏻‍💻 What does this PR do?

Run yarn install inside docker container for 'dev' mode and reduce docker image size by removing cache and refactoring Docker file to be more multi stage (removed yarn install as separate step in dockerise.yaml and the pre-requisite intermediate docker container, i found that copying node_modules doesn't work very well, since there are symlinks etc.. that are lost), currently making a tag to test this (in omsupply fork, to not trigger all of the builds)

Update docker readme to reflect these changes

Exclude generated.ts from backend plugin build, there is a comment in backend-tsconfig.json

Re-generate backend types (with cli)

Added the same resolve option from host webpack config to frontend webpack config:  `conditionNames: ['require', '...']`, this is the alternative to: https://github.com/msupply-foundation/open-msupply/pull/8324

## 💌 Any notes for the reviewer?

Changes here don't effect any core code so should be safe in 2.9

# 🧪 Testing

As per issue, dev testing only.

I've tried with the tag i've build, v2.9.0-RC-8481-dev (you can see the size in dockerhub is smaller for both dev and non dev build of that tag: https://hub.docker.com/repository/docker/msupplyfoundation/omsupply/tags).

run "IMAGE_TAG=v2.9.0-RC-8481-dev cargo run" in test directory in st plugin and in this branch of civ plugin: https://github.com/msupply-foundation/civ-plugins/tree/Build-only (not ST plugin now fails due to migrations and for received status, but plugin build works)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/plugins/stPlugins
Comment (lache-melvin) [inline client/packages/plugins/stPlugins:1]: we really ought to prevent these submodule references getting checked in, can they be added to a gitignore?

**Review by lache-melvin — APPROVED** [review]
They build for me 🎉 🎉 

Not quite in scope of this PR, but the other workflow, `trigger-plugin-tests` - I think would be a good idea to move REPOS list to a GH env var rather than explicitly in the workflow file? Seeing as this is an open source repo and can be forked/cloned, we should only want those repos known to us here 👀

File: client/packages/plugins/stPlugins
Comment (andreievg) [reply client/packages/plugins/stPlugins:1]: Thanks, I undid it.
[Added extra thing to carry over](https://github.com/msupply-foundation/open-msupply/issues/2951). Yeah I think ignoring everything in the plugins folder apart from the core would be better, although it sounds like we will be cloning repos at that point rather then adding as submodules, which probably makes more sense

**Comment by andreievg** [comment]
Thank you for review @lache-melvin !
